#!/usr/bin/env python3
"""
Dataset de países para GeoQuiz Battle
Contiene datos reales de países principales
"""

COUNTRIES_DATA = [
    {
        "name": {"common": "España", "native": "España"},
        "cca2": "ES",
        "cca3": "ESP",
        "capital": ["Madrid"],
        "population": 47450795,
        "area": 505990.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/es.png"},
        "borders": ["PRT", "FRA", "AND", "GBR", "MAR"],
        "languages": {"spa": "Español"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Francia", "native": "France"},
        "cca2": "FR",
        "cca3": "FRA",
        "capital": ["París"],
        "population": 65273511,
        "area": 551695.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/fr.png"},
        "borders": ["BEL", "DEU", "CHE", "ITA", "ESP", "AND", "MCO", "LUX"],
        "languages": {"fra": "Francés"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Alemania", "native": "Deutschland"},
        "cca2": "DE",
        "cca3": "DEU",
        "capital": ["Berlín"],
        "population": 83240525,
        "area": 357114.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/de.png"},
        "borders": ["DNK", "POL", "CZE", "AUT", "CHE", "FRA", "LUX", "BEL", "NLD"],
        "languages": {"deu": "Alemán"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Italia", "native": "Italia"},
        "cca2": "IT",
        "cca3": "ITA",
        "capital": ["Roma"],
        "population": 59554023,
        "area": 301336.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/it.png"},
        "borders": ["AUT", "SVN", "CHE", "FRA", "VAT", "SMR", "AUT", "HRV"],
        "languages": {"ita": "Italiano"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Portugal", "native": "Portugal"},
        "cca2": "PT",
        "cca3": "PRT",
        "capital": ["Lisboa"],
        "population": 10331926,
        "area": 92212.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/pt.png"},
        "borders": ["ESP"],
        "languages": {"por": "Portugués"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Reino Unido", "native": "United Kingdom"},
        "cca2": "GB",
        "cca3": "GBR",
        "capital": ["Londres"],
        "population": 67326569,
        "area": 242495.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/gb.png"},
        "borders": ["IRL"],
        "languages": {"eng": "Inglés"},
        "currencies": {"GBP": {"name": "Libra esterlina", "symbol": "£"}}
    },
    {
        "name": {"common": "Estados Unidos", "native": "United States"},
        "cca2": "US",
        "cca3": "USA",
        "capital": ["Washington, D.C."],
        "population": 331893745,
        "area": 9372610.0,
        "region": "Americas",
        "flags": {"png": "https://flagcdn.com/w320/us.png"},
        "borders": ["CAN", "MEX"],
        "languages": {"eng": "Inglés"},
        "currencies": {"USD": {"name": "Dólar estadounidense", "symbol": "$"}}
    },
    {
        "name": {"common": "Canadá", "native": "Canada"},
        "cca2": "CA",
        "cca3": "CAN",
        "capital": ["Ottawa"],
        "population": 38005238,
        "area": 9984670.0,
        "region": "Americas",
        "flags": {"png": "https://flagcdn.com/w320/ca.png"},
        "borders": ["USA"],
        "languages": {"eng": "Inglés", "fra": "Francés"},
        "currencies": {"CAD": {"name": "Dólar canadiense", "symbol": "$"}}
    },
    {
        "name": {"common": "México", "native": "México"},
        "cca2": "MX",
        "cca3": "MEX",
        "capital": ["Ciudad de México"],
        "population": 128932753,
        "area": 1964375.0,
        "region": "Americas",
        "flags": {"png": "https://flagcdn.com/w320/mx.png"},
        "borders": ["USA", "BLZ", "GTM"],
        "languages": {"spa": "Español"},
        "currencies": {"MXN": {"name": "Peso mexicano", "symbol": "$"}}
    },
    {
        "name": {"common": "Brasil", "native": "Brasil"},
        "cca2": "BR",
        "cca3": "BRA",
        "capital": ["Brasilia"],
        "population": 214326223,
        "area": 8515767.0,
        "region": "Americas",
        "flags": {"png": "https://flagcdn.com/w320/br.png"},
        "borders": ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
        "languages": {"por": "Portugués"},
        "currencies": {"BRL": {"name": "Real brasileño", "symbol": "R$"}}
    },
    {
        "name": {"common": "Argentina", "native": "Argentina"},
        "cca2": "AR",
        "cca3": "ARG",
        "capital": ["Buenos Aires"],
        "population": 45805823,
        "area": 2780400.0,
        "region": "Americas",
        "flags": {"png": "https://flagcdn.com/w320/ar.png"},
        "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
        "languages": {"spa": "Español"},
        "currencies": {"ARS": {"name": "Peso argentino", "symbol": "$"}}
    },
    {
        "name": {"common": "China", "native": "中国"},
        "cca2": "CN",
        "cca3": "CHN",
        "capital": ["Pekín"],
        "population": 1411778724,
        "area": 9706961.0,
        "region": "Asia",
        "flags": {"png": "https://flagcdn.com/w320/cn.png"},
        "borders": ["AFG", "BTN", "IND", "KAZ", "PRK", "KGZ", "LAO", "MNG", "MMR", "NPL", "PAK", "RUS", "TJK", "VNM"],
        "languages": {"zho": "Chino"},
        "currencies": {"CNY": {"name": "Yuan chino", "symbol": "¥"}}
    },
    {
        "name": {"common": "Japón", "native": "日本"},
        "cca2": "JP",
        "cca3": "JPN",
        "capital": ["Tokio"],
        "population": 125681593,
        "area": 377930.0,
        "region": "Asia",
        "flags": {"png": "https://flagcdn.com/w320/jp.png"},
        "borders": [],
        "languages": {"jpn": "Japonés"},
        "currencies": {"JPY": {"name": "Yen japonés", "symbol": "¥"}}
    },
    {
        "name": {"common": "India", "native": "भारत"},
        "cca2": "IN",
        "cca3": "IND",
        "capital": ["Nueva Delhi"],
        "population": 1406631776,
        "area": 3287263.0,
        "region": "Asia",
        "flags": {"png": "https://flagcdn.com/w320/in.png"},
        "borders": ["BGD", "BTN", "MMR", "CHN", "NPL", "PAK"],
        "languages": {"hin": "Hindi", "eng": "Inglés"},
        "currencies": {"INR": {"name": "Rupia india", "symbol": "₹"}}
    },
    {
        "name": {"common": "Australia", "native": "Australia"},
        "cca2": "AU",
        "cca3": "AUS",
        "capital": ["Canberra"],
        "population": 25687041,
        "area": 7692024.0,
        "region": "Oceania",
        "flags": {"png": "https://flagcdn.com/w320/au.png"},
        "borders": [],
        "languages": {"eng": "Inglés"},
        "currencies": {"AUD": {"name": "Dólar australiano", "symbol": "$"}}
    },
    {
        "name": {"common": "Rusia", "native": "Россия"},
        "cca2": "RU",
        "cca3": "RUS",
        "capital": ["Moscú"],
        "population": 145912025,
        "area": 17098242.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/ru.png"},
        "borders": ["NOR", "FIN", "EST", "LVA", "LTU", "BLR", "UKR", "GEO", "AZE", "KAZ", "CHN", "MNG", "PRK"],
        "languages": {"rus": "Ruso"},
        "currencies": {"RUB": {"name": "Rublo ruso", "symbol": "₽"}}
    },
    {
        "name": {"common": "Corea del Sur", "native": "대한민국"},
        "cca2": "KR",
        "cca3": "KOR",
        "capital": ["Seúl"],
        "population": 51844886,
        "area": 100210.0,
        "region": "Asia",
        "flags": {"png": "https://flagcdn.com/w320/kr.png"},
        "borders": ["PRK"],
        "languages": {"kor": "Coreano"},
        "currencies": {"KRW": {"name": "Won surcoreano", "symbol": "₩"}}
    },
    {
        "name": {"common": "Brasil", "native": "Brasil"},
        "cca2": "BR",
        "cca3": "BRA",
        "capital": ["Brasilia"],
        "population": 214326223,
        "area": 8515767.0,
        "region": "Americas",
        "flags": {"png": "https://flagcdn.com/w320/br.png"},
        "borders": ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
        "languages": {"por": "Portugués"},
        "currencies": {"BRL": {"name": "Real brasileño", "symbol": "R$"}}
    },
    {
        "name": {"common": "Nigeria", "native": "Nigeria"},
        "cca2": "NG",
        "cca3": "NGA",
        "capital": ["Abuya"],
        "population": 213401323,
        "area": 923768.0,
        "region": "Africa",
        "flags": {"png": "https://flagcdn.com/w320/ng.png"},
        "borders": ["BEN", "CMR", "TCD", "NER", "TGO", "BWA"],
        "languages": {"eng": "Inglés"},
        "currencies": {"NGN": {"name": "Naira nigeriano", "symbol": "₦"}}
    },
    {
        "name": {"common": "Egipto", "native": "مصر"},
        "cca2": "EG",
        "cca3": "EGY",
        "capital": ["El Cairo"],
        "population": 109262178,
        "area": 1010408.0,
        "region": "Africa",
        "flags": {"png": "https://flagcdn.com/w320/eg.png"},
        "borders": ["LBY", "SDN", "ISR"],
        "languages": {"ara": "Árabe"},
        "currencies": {"EGP": {"name": "Libra egipcia", "symbol": "£"}}
    },
    {
        "name": {"common": "Sudáfrica", "native": "South Africa"},
        "cca2": "ZA",
        "cca3": "ZAF",
        "capital": ["Pretoria"],
        "population": 59308690,
        "area": 1221037.0,
        "region": "Africa",
        "flags": {"png": "https://flagcdn.com/w320/za.png"},
        "borders": ["LSO", "MOZ", "SWZ", "ZMB", "BWA", "ZWE", "NAM"],
        "languages": {"afr": "Afrikaans", "eng": "Inglés"},
        "currencies": {"ZAR": {"name": "Rand sudafricano", "symbol": "R"}}
    },
    {
        "name": {"common": "Turquía", "native": "Türkiye"},
        "cca2": "TR",
        "cca3": "TUR",
        "capital": ["Ankara"],
        "population": 85042738,
        "area": 783562.0,
        "region": "Asia",
        "flags": {"png": "https://flagcdn.com/w320/tr.png"},
        "borders": ["ARM", "AZE", "GEO", "BGR", "GRC", "IRN", "IRQ", "SYR"],
        "languages": {"tur": "Turco"},
        "currencies": {"TRY": {"name": "Lira turca", "symbol": "₺"}}
    },
    {
        "name": {"common": "Polonia", "native": "Polska"},
        "cca2": "PL",
        "cca3": "POL",
        "capital": ["Varsovia"],
        "population": 37797006,
        "area": 312696.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/pl.png"},
        "borders": ["DEU", "CZE", "SVK", "UKR", "BLR", "LTU", "RUS"],
        "languages": {"pol": "Polaco"},
        "currencies": {"PLN": {"name": "Złoty polaco", "symbol": "zł"}}
    },
    {
        "name": {"common": "Países Bajos", "native": "Nederland"},
        "cca2": "NL",
        "cca3": "NLD",
        "capital": ["Ámsterdam"],
        "population": 17534942,
        "area": 41543.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/nl.png"},
        "borders": ["BEL", "DEU"],
        "languages": {"nld": "Neerlandés"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Bélgica", "native": "België"},
        "cca2": "BE",
        "cca3": "BEL",
        "capital": ["Bruselas"],
        "population": 11589623,
        "area": 30528.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/be.png"},
        "borders": ["FRA", "DEU", "LUX", "NLD"],
        "languages": {"nld": "Neerlandés", "fra": "Francés", "deu": "Alemán"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Suiza", "native": "Schweiz"},
        "cca2": "CH",
        "cca3": "CHE",
        "capital": ["Berna"],
        "population": 8654622,
        "area": 41284.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/ch.png"},
        "borders": ["FRA", "DEU", "AUT", "ITA", "LIE"],
        "languages": {"deu": "Alemán", "fra": "Francés", "ita": "Italiano"},
        "currencies": {"CHF": {"name": "Franco suizo", "symbol": "Fr"}}
    },
    {
        "name": {"common": "Austria", "native": "Österreich"},
        "cca2": "AT",
        "cca3": "AUT",
        "capital": ["Viena"],
        "population": 8932664,
        "area": 83879.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/at.png"},
        "borders": ["DEU", "CZE", "SVK", "HUN", "SVN", "ITA", "CHE", "LIE"],
        "languages": {"deu": "Alemán"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Suecia", "native": "Sverige"},
        "cca2": "SE",
        "cca3": "SWE",
        "capital": ["Estocolmo"],
        "population": 10416196,
        "area": 450295.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/se.png"},
        "borders": ["NOR", "FIN"],
        "languages": {"swe": "Sueco"},
        "currencies": {"SEK": {"name": "Corona sueca", "symbol": "kr"}}
    },
    {
        "name": {"common": "Noruega", "native": "Norge"},
        "cca2": "NO",
        "cca3": "NOR",
        "capital": ["Oslo"],
        "population": 5391369,
        "area": 323802.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/no.png"},
        "borders": ["SWE", "FIN", "RUS"],
        "languages": {"nor": "Noruego"},
        "currencies": {"NOK": {"name": "Corona noruega", "symbol": "kr"}}
    },
    {
        "name": {"common": "Grecia", "native": "Ελλάδα"},
        "cca2": "GR",
        "cca3": "GRC",
        "capital": ["Atenas"],
        "population": 10724599,
        "area": 131957.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/gr.png"},
        "borders": ["ALB", "MKD", "BGR", "TUR"],
        "languages": {"ell": "Griego"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Irlanda", "native": "Ireland"},
        "cca2": "IE",
        "cca3": "IRL",
        "capital": ["Dublín"],
        "population": 5041425,
        "area": 70273.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/ie.png"},
        "borders": ["GBR"],
        "languages": {"eng": "Inglés", "gle": "Irlandés"},
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}}
    },
    {
        "name": {"common": "Dinamarca", "native": "Danmark"},
        "cca2": "DK",
        "cca3": "DNK",
        "capital": ["Copenhague"],
        "population": 5932654,
        "area": 43094.0,
        "region": "Europe",
        "flags": {"png": "https://flagcdn.com/w320/dk.png"},
        "borders": ["DEU"],
        "languages": {"dan": "Danés"},
        "currencies": {"DKK": {"name": "Corona danesa", "symbol": "kr"}}
    }
]
